import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  // Mirror the directories that `next lint` used to ignore implicitly.
  // ESLint flat config doesn't honor .eslintignore — ignores must live
  // here. Without this, `npm run lint` walks .next/, node_modules/, and
  // emits ~44k irrelevant findings from generated bundles.
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "out/**",
      "build/**",
      "dist/**",
      "coverage/**",
      "drizzle/meta/**",
      "public/**",
      "*.config.js",
      "*.config.mjs",
      // Auto-generated by Next.js — uses the triple-slash reference
      // syntax that next/typescript flags. Not user-maintained.
      "next-env.d.ts",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default eslintConfig;
