import { NextRequest, NextResponse } from "next/server";
import { getClaudeClient } from "@/lib/claude";
import { gatherMarketContext } from "@/lib/market-context";
import { db } from "@/lib/db";
import { marketDigests, users, discordWebhooks, articles } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { createRouteLogger } from "@/lib/logger";
import { safeCompare } from "@/lib/crypto";
import { sendAlertEmail } from "@/lib/email";
import { getOrCreateBeacontryDeskUser } from "@/lib/system-users";
import { getEasternToday } from "@/lib/market-day";

const log = createRouteLogger("cron-market-digest");

export async function GET(request: NextRequest) {
  const secret = request.headers.get("x-cron-secret");
  const expected = process.env.CRON_SECRET;

  if (!expected || !secret || !safeCompare(secret, expected)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const claude = getClaudeClient();
  if (!(await claude.isConfigured())) {
    return NextResponse.json({ error: "LLM not configured — set GROQ_API_KEY in admin → System Config" }, { status: 503 });
  }

  // ET-keyed (not UTC) so a manual retry before 4 AM ET doesn't write
  // a "tomorrow" row that the real 9 AM ET cron then collides with.
  const today = getEasternToday();

  try {
    // Check if already generated today
    const [existing] = await db
      .select()
      .from(marketDigests)
      .where(eq(marketDigests.date, today))
      .limit(1);

    if (existing) {
      return NextResponse.json({ status: "already_generated", date: today });
    }

    // Gather context and generate (bypass rate limit for cron)
    const context = await gatherMarketContext();
    const result = await claude.generateMarketDigest(context, true);

    // Persist
    await db.insert(marketDigests).values({
      date: today,
      summary: result.summary,
      watchlistSymbols: context.recentSignals?.map((s: { symbol: string }) => s.symbol) ?? [],
      newsContext: context.news ?? [],
      signalContext: context.recentSignals ?? [],
    });

    // Articles auto-populate
    //
    // The Articles page (/dashboard/articles) was reported empty because
    // nothing was seeding it. Today's market digest is published as a
    // free Article so users get a permanent, searchable record.
    //
    // Author attribution: a dedicated "Beacontry Desk" system user (see
    // src/lib/system-users.ts) owns these rows so real admins' names
    // don't show up on the byline. The API joins users.name for display,
    // and that user is named "Beacontry Desk".
    //
    // Idempotent: slug = `market-digest-{YYYY-MM-DD}`. If this cron
    // re-fires, the slug unique index catches the dup and we skip.
    try {
      const deskUserId = await getOrCreateBeacontryDeskUser();
      const slug = `market-digest-${today}`;
      const titleDate = new Date(today + "T12:00:00Z").toLocaleDateString(
        "en-US",
        { month: "long", day: "numeric", year: "numeric" }
      );
      const body =
        `**Beacontry Daily Desk · ${titleDate}**\n\n` +
        result.summary +
        `\n\n---\n\n_Generated by Beacontry's market intelligence pipeline. Not investment advice. ` +
        `See /risk for the full risk disclosure._`;
      await db
        .insert(articles)
        .values({
          authorId: deskUserId,
          title: `Daily Market Digest — ${titleDate}`,
          slug,
          body,
          category: "Daily Digest",
          price: 0,
          publishedAt: new Date(),
        })
        .onConflictDoNothing();
      log.info({ slug }, "Daily digest published as article");
    } catch (err) {
      // Don't let article-write failures break the digest cron — the
      // primary deliverables (Discord/email) are more important than
      // the article surface.
      log.warn(
        { err: err instanceof Error ? err.message : "unknown" },
        "Failed to publish digest as article"
      );
    }

    // Send notifications to all users with Discord webhooks
    const webhooks = await db
      .select({ webhookUrl: discordWebhooks.webhookUrl })
      .from(discordWebhooks)
      .where(eq(discordWebhooks.enabled, true));

    let notified = 0;
    for (const wh of webhooks) {
      try {
        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 5000);
        try {
          await fetch(wh.webhookUrl, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              username: "Beacontry",
              embeds: [{
                title: `Daily Market Digest — ${today}`,
                description: result.summary.slice(0, 4000),
                color: 0x3b82f6,
                footer: { text: "Beacontry AI Market Intelligence" },
                timestamp: new Date().toISOString(),
              }],
            }),
            signal: controller.signal,
          });
          notified++;
        } finally {
          clearTimeout(timeout);
        }
      } catch {
        // Best-effort delivery
      }
    }

    // Push notifications + email (per-user opt-in for email; push goes to
    // everyone with a subscription). Each channel is best-effort; one
    // failure shouldn't block the others.
    const allUsers = await db
      .select({
        id: users.id,
        email: users.email,
        notificationEmail: users.notificationEmail,
        digestEmailOptIn: users.digestEmailOptIn,
      })
      .from(users);

    let emailed = 0;
    for (const user of allUsers) {
      try {
        const { sendPushToUser } = await import("@/lib/push");
        await sendPushToUser(user.id, {
          title: "Daily Market Digest",
          body: result.summary.slice(0, 200) + "...",
          url: "/dashboard",
        }).catch(() => {});
      } catch {
        // Push module may not be available
      }

      // Email — only opted-in users. Prefer notificationEmail (so trade
      // alerts and the digest can route to different inboxes), fall back
      // to login email.
      if (user.digestEmailOptIn) {
        const recipient = user.notificationEmail ?? user.email;
        try {
          const sent = await sendAlertEmail(
            recipient,
            `Daily Market Digest — ${today}`,
            result.summary
          );
          if (sent.success) emailed++;
        } catch {
          // Per-user failure shouldn't block others
        }
      }
    }

    return NextResponse.json({
      status: "generated",
      date: today,
      tokensUsed: result.tokensUsed,
      notifiedWebhooks: notified,
      emailed,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    log.error({ err: message }, "Market digest cron error");
    return NextResponse.json(
      { error: "Digest generation failed" },
      { status: 500 }
    );
  }
}
